steps:
  - label: ":npm:"
    command: "npm install && npm test"
  - wait
  - label: "Script that fails"
    command: "step-types-example/failure.sh"
  - wait: ~
    continue_on_failure: true
  - label: "Script that uploads logs as an artifact"
    command: "step-types-example/upload.sh"
  - block: "Please click me to continue"
  - label: "Uploads to S3"
    command: "step-types-example/s3upload.sh"
  - block: "Deployment target"
    fields: 
      - select: "Target"
        key: "deploy-target"
        options:
          - label: "Target 1"
            value: "t1"
          - label: "Target 2"
            value: "t2"
  - trigger: "deploy"
    branches: "master"
    build:
      meta_data:
        release-version: "1.1"