steps:
  - label: ":npm:"
    command: "npm install && npm test"
  - wait
  - label: "Script that might fail"
    command: "step-types-example/failure.sh"
  - wait: ~
    continue_on_failure: true
  - label: "Script that uploads logs as an artifact"
    command: "step-types-example/upload.sh"
  - block: "Please click me to continue"
  - label: "Uploads to S3"
    command: "step-types-example/s3upload.sh"
  - wait
  - command: ".buildkite/pipeline.deployment.yml.sh | buildkite-agent pipeline upload"
  - wait
  - trigger: "deploy"
    branches: "master"
    build:
      meta_data:
        release-version: "1.1"